### PR TITLE
Updating Routers and Model table names

### PR DESCRIPTION
**Pull request by calvarezberrios**
Updated table names in routers and models to match the migrations database model.

### CODE REVIEW

**Comment by calvarezberrios** [comment]
All endpoints and models have been updated to have the updated table names and fields as updated in the database schema.
[Database Schema](https://app.dbdesigner.net/designer/schema/0-untitled-7585040f-5d37-44a9-ae46-334bf822aeae)

**Comment by calvarezberrios** [comment]
the endpoint urls are the same as before, frontend can use the endpoint the same way as it was originally made.

**Comment by lgv-0** [comment]
Do we have any updates on this @calvarezberrios

**Comment by calvarezberrios** [comment]
> Do we have any updates on this @calvarezberrios

This is from the beginning related to the merge that was reverted back. This is just a draft, I’ll close it since it is not going to be used.

**Pull request closed without merging**
